apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-processor-scaler
  namespace: bank-of-singapore-demo5-1776851589
spec:
  scaleTargetRef:
    name: payment-processor
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: my-cluster-kafka-bootstrap.bank-of-singapore-demo5-1776851589.svc.cluster.local:9092
        consumerGroup: payment-processor-group
        topic: payment-events
        lagThreshold: "1000"
        activationLagThreshold: "100"
        offsetResetPolicy: latest