# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: payments
    tier: backend
  name: payment-processor
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: payment-processor
    application: bank-of-anthos
    environment: development
    team: payments
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: payments
    tier: backend
  name: payment-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-processor
      application: bank-of-anthos
      environment: development
      team: payments
      tier: backend
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: payment-processor
        application: bank-of-anthos
        environment: development
        team: payments
        tier: backend
    spec:
      containers:
        - env:
            - name: DD_SERVICE
              value: payment-processor
            - name: DD_ENV
              value: evaluation-poc-cluster
            - name: VERSION
              value: v0.6.8
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "false"
            - name: ENABLE_METRICS
              value: "false"
            - name: LOG_LEVEL
              value: info
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: KAFKA_CONSUMER_GROUP
              value: "payment-processor-group"
            - name: KAFKA_TOPIC
              value: "payment-events"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: environment-config
          image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/payment-processor:v0.6.8
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 2
          name: payment-processor
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 0.5Gi
              memory: 512Mi
            requests:
              cpu: 100m
              ephemeral-storage: 0.5Gi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: bank-of-anthos
      terminationGracePeriodSeconds: 5
      volumes:
        - emptyDir: {}
          name: tmp
